name: Build website

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i
      - run: npm run build
      - name: _just
        uses: js-just/latest@main
      - run: npm run docs:build
      - run: |
          mkdir -p dist/docs
          cp -r docs/.vitepress/dist/* dist/docs/
          cp CNAME dist/CNAME
          cp dist/index.html dist/404.html
          rm index.html
      - run: cp index.html dist/download.html
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "dist"
          destination-github-username: JustDeveloper1
          destination-repository-name: "JSSC.js.org"
          target-branch: "gh-pages"
          target-directory: "website"
